language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - pytest
    - coverage run --source=api.v1 -m pytest && coverage report

after_success:
    - coveralls