language: python
python:
    - "3.6"
    - "3.7"

install:
     - pip install -r requirements.txt
     - pip install coveralls
     - pip install pytest-cov

script:
    - python -m pytest --cov=app
    - coveralls
  
after_success:
  - coveralls
